sb/sb/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from .views import IndexView, CustomerCreateView

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^new/$', CustomerCreateView.as_view(), name='add'),
]

sb/sb/models.py
from django.db import models


class Customer(models.Model):
    name = models.CharField(max_length=200)
    doc = models.CharField(max_length=200)
    email = models.EmailField()
    phone = models.CharField(max_length=200)
    date = models.DateTimeField(auto_now_add=True, blank=True)

    def get_address(self):
        return Address.objects.filter(customer_id=self.id)

    def get_site(self):
        return Site.objects.filter(customer_id=self.id)


class Site(models.Model):
   customer_id = models.ForeignKey(Customer)
   url = models.URLField()


class Address(models.Model):
    BRAZIL_STATES = (('', u''),
                     ('AC', u'Acre'),
                     ('AL', u'Alagoas'),
                     ('AP', u'Amapá'),
                     ('AM', u'Amazonas'),
                     ('BA', u'Bahia'),
                     ('CE', u'Ceará'),
                     ('DF', u'Distrito Federal'),
                     ('ES', u'Espírito Santo'),
                     ('GO', u'Goiás'),
                     ('MA', u'Maranhão'),
                     ('MT', u'Mato Grosso'),
                     ('MS', u'Mato Grosso do Sul'),
                     ('MG', u'Minas Gerais'),
                     ('PA', u'Pará'),
                     ('PB', u'Paraíba'),
                     ('PR', u'Paraná'),
                     ('PE', u'Pernambuco'),
                     ('PI', u'Piauí'),
                     ('RJ', u'Rio de Janeiro'),
                     ('RN', u'Rio Grande do Norte'),
                     ('RS', u'Rio Grande do Sul'),
                     ('RO', u'Rondônia'),
                     ('RR', u'Roraima'),
                     ('SC', u'Santa Catarina'),
                     ('SP', u'São Paulo'),
                     ('SE', u'Sergipe'),
                     ('TO', u'Tocantins'))

    customer_id = models.ForeignKey(Customer)
    street = models.CharField(max_length=200)
    number = models.IntegerField()
    district = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    state = models.CharField(max_length=2,
                             choices=BRAZIL_STATES)

sb/sb/forms.py
from django.forms import ModelForm
from django.forms.models import inlineformset_factory

from .models import Customer, Address, Site


class CustomerForm(ModelForm):
    class Meta:
        model = Customer
        exclude = ['date']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
        })


AddressFormSet = inlineformset_factory(Customer, Address, exclude=['date'], form=CustomerForm)
SiteFormSet = inlineformset_factory(Customer, Site, exclude=['date'], form=CustomerForm)

sb/sb/views.py
from django.http import HttpResponseRedirect
from django.views import generic

from .forms import CustomerForm, AddressFormSet, SiteFormSet
from .models import Customer, Address, Site


class IndexView(generic.ListView):
    template_name = 'sb/index.html'
    context_object_name = 'customer_list'

    def get_queryset(self):
        return Customer.objects.order_by('-date')


class CustomerCreateView(generic.CreateView):
    template_name = 'sb/customer_form.html'
    model = Customer
    form_class = CustomerForm
    success_url = '/'

    def get(self, request, *args, **kwargs):
        """
        Handles GET requests and instantiates blank versions of the form
        and its inline formsets.
        """
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        address_form = AddressFormSet()
        site_form = SiteFormSet()
        return self.render_to_response(
            self.get_context_data(form=form,
                                  address_form=address_form,
                                  site_form=site_form))

    def post(self, request, *args, **kwargs):
        """
        Handles POST requests, instantiating a form instance and its inline
        formsets with the passed POST variables and then checking them for
        validity.
        """
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        address_form = AddressFormSet(self.request.POST)
        site_form = SiteFormSet(self.request.POST)
        if (form.is_valid() and address_form.is_valid() and
            site_form.is_valid()):
            return self.form_valid(form, address_form, site_form)
        else:
            return self.form_invalid(form, address_form, site_form)

    def form_valid(self, form, address_form, site_form):
        """
        Called if all forms are valid. Creates a Recipe instance along with
        associated Ingredients and Instructions and then redirects to a
        success page.
        """
        self.object = form.save()
        address_form.instance = self.object
        address_form.save()
        site_form.instance = self.object
        site_form.save()
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form, address_form, site_form):
        """
        Called if a form is invalid. Re-renders the context data with the
        data-filled forms and errors.
        """
        return self.render_to_response(
            self.get_context_data(form=form,
                                  address_form=address_form,
                                  site_form=site_form))

sb/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>SB Challenge</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

    <nav class="navbar navbar-default">
      <div class="container-fluid">
         <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'index' %}">SB Challenge</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'index' %}">Customers list</a></li>
            <li><a href="{% url 'add' %}">Add customer</a></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    
    <div class="container">
        {% block content %}{% endblock %}
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.maskedinput/1.4.1/jquery.maskedinput.js"></script>

    {% block js %}{% endblock %}
  </body>
</html>

sb/templates/sb/customer_form.html
{% extends "base.html" %}

{% block content %}

    <h1>Add customer</h1>

    <form method="post" action=".">
        {% csrf_token %}
        <div class="col-md-4">
            <fieldset>
                <legend>Customer</legend>
                <div class="form-group">
                    {{ form.name.errors }}
                    {{ form.name.label_tag }}
                    {{ form.name }}
                </div>
                <div class="form-group">
                    {{ form.doc.errors }}
                    {{ form.doc.label_tag }}
                    {{ form.doc }}
                </div>
                <div class="form-group">
                    {{ form.email.errors }}
                    {{ form.email.label_tag }}
                    {{ form.email }}
                </div>
                <div class="form-group">
                    {{ form.phone.errors }}
                    {{ form.phone.label_tag }}
                    {{ form.phone }}
                </div>
            </fieldset>
        </div>
        <div class="col-md-4">
            <fieldset>
                <legend>Address</legend>
                {{ address_form.management_form }}
                {{ address_form.non_form_errors }}
                {% for form in address_form|slice:":1" %}
                    {{ form.id }}
                    <div class="inline {{ address_form.prefix }}">
                        <div class="form-group">
                            {{ form.street.errors }}
                            {{ form.street.label_tag }}
                            {{ form.street }}
                        </div>
                        <div class="form-group">
                            {{ form.number.errors }}
                            {{ form.number.label_tag }}
                            {{ form.number }}
                        </div>
                        <div class="form-group">
                            {{ form.district.errors }}
                            {{ form.district.label_tag }}
                            {{ form.district }}
                        </div>
                        <div class="form-group">
                            {{ form.city.errors }}
                            {{ form.city.label_tag }}
                            {{ form.city }}
                        </div>
                        <div class="form-group">
                            {{ form.state.errors }}
                            {{ form.state.label_tag }}
                            {{ form.state }}
                        </div>
                    </div>
                {% endfor %}
            </fieldset>
        </div>
        <div class="col-md-4">
            <fieldset id="sites">
                <legend>Sites <a href="javascript:void(0);" id="add_site">+</a></legend>
                {{ site_form.management_form }}
                {{ site_form.non_form_errors }}
                {% for form in site_form %}
                    {{ form.id }}
                    <div class="inline {{ site_form.prefix }}">
                        <div class="form-group">
                            {{ form.url.errors }}
                            {{ form.url.label_tag }}
                            {{ form.url }}
                        </div>
                    </div>
                {% endfor %}
            </fieldset>
            <input type="submit" value="Add customer" class="submit btn btn-default" />
        </div>
    </form>

{% endblock %}

{% block js %}
    <script type="text/javascript">
        $(document).ready(function(){
            $("#id_doc").mask("999.999.999-99");
            $('#id_phone').mask("(99) 9999-9999?9").ready(function(event) {
                var target, phone, element;
                target = (event.currentTarget) ? event.currentTarget : event.srcElement;
                phone = target.value.replace(/\D/g, '');
                element = $(target);
                element.unmask();
                if(phone.length > 10) {
                    element.mask("(99) 99999-999?9");
                } else {
                    element.mask("(99) 9999-9999?9");  
                }
            });

            var count = 3;

            $('#add_site').click(function(){
                html = '<input id="id_site_set-'+count+'-id" name="site_set-'+count+'-id" type="hidden">' +
                        '<div class="inline site_set">' +
                            '<div class="form-group">' +
                                '<label for="id_site_set-'+count+'-url">Url:</label>'+
                                '<input class="form-control" id="id_site_set-'+count+'-url" maxlength="200" name="site_set-'+count+'-url" type="url">' +
                            '</div>' +
                        '</div>';
                count++;
                $('#id_site_set-TOTAL_FORMS').val(count);
                $('#sites').append(html);
            });

        });
    </script>
{% endblock %}

sb/templates/sb/index.html
{% extends "base.html" %}

{% block content %}

    <h1>Customer list</h1>

    {% if customer_list %}
        <div class="row">
        {% for customer in customer_list %}
            {% if forloop.counter0|divisibleby:3 %}
                </div>
                <div class="row">
            {% endif %}
            <div class="col-md-4">
                <dl class="dl-horizontal">
                    <dt>Name</dt>
                    <dd>{{ customer.name }}</dd>
                    <dt>Doc</dt>
                    <dd>{{ customer.doc }}</dd>
                    <dt>Phone</dt>
                    <dd>{{ customer.phone }}</dd>
                    <dt>Email</dt>
                    <dd>{{ customer.email }}</dd>
                    <dt>Endereço</dt>
                    <dd>
                    {% for address in customer.get_address %}
                        <ul class="list-unstyled">
                            <li>{{ address.street }}, {{ address.number }} - {{ address.district }} - {{ address.city }}, {{ address.state }}</li>
                        </ul>
                    {% endfor %}
                    </dd>
                    <dt>Sites</dt>
                    <dd>
                    {% for site in customer.get_site %}
                        <ul class="list-unstyled">
                            <li>{{ site.url }}</li>
                        </ul>
                    {% endfor %}
                    </dd>
                </dl>
            </div>
        {% endfor %}
        </div>
    {% else %}
        <p class="text-center">No customers are available.</p>
    {% endif %}

{% endblock %}